### ISSUE TITLE
Used firefox window is always displaying "- Mozilla Firefox Private Browsing"

### ISSUE THREAD

**Issue by Kukulkano** [alifcommunity/webui#53]
First, impresive tool and very good idea!

I just ran the golang example code. This is the result (dark mode on my screen):
[image on imgur](https://i.imgur.com/HkpmCkb.png)

No matter how I edit the <title> flag, it is always showing that "_- Mozilla Firefox Private Browsing_" extension and title.

Also, the title is always shown twice? The second one should be gone, right? This is what the window title bar is normally used for...

I'm on OpenSUSE LEAP 15.4 (x64)

**Comment by AlbertShown** [comment]
Hi @Kukulkano, and thank you for the feedback.

WebUI uses the private browsing mode, but it's not mandatory.
[Here](https://github.com/alifcommunity/webui/blob/0c1504835e6053dc5f1f8f6a2b623833a6d447c8/src/webui.c#LL2169C59-L2169C59) is how WebUI runs Firefox: `-P WebUI -purgecaches -new-window -private-window`. You can, for now, remove `-private-window` and re-build WebUI using any C compiler. We will also add an easy way to disable the private browsing mode soon.

The double title may be because of the custom styling WebUI uses. You can edit it to improve the UI.
`/tmp/.WebUI/WebUIFirefoxProfile/chrome/userChrome.css`. 
If you make the UI (title bar) look better, please share the CSS style here.

Please remember that the UI (title bar) issue exists only in Firefox. While Chrome & Edge works fine.
You can easily switch to Chrome in your Go code by setting your preferred web browser:

```go
// Show window
webui.Show(my_window, login_html, webui.Chrome)
webui.Show(my_window, login_html, webui.Edge)
webui.Show(my_window, login_html, webui.Firefox)
webui.Show(my_window, login_html, webui.Safari)
webui.Show(my_window, login_html, webui.Chromium)
webui.Show(my_window, login_html, webui.AnyBrowser)
```

**Comment by Kukulkano** [comment]
Thank you!
