### ISSUE TITLE
Exemples or direction for macOS

### ISSUE THREAD

**Issue by MartyLake** [alifcommunity/webui#73]
Hey,
I tried evaluating the library, but I failed to find exemples or direction for macOS.
Maybe I didn’t look enough? If so would you be so kind to point me to the RTFM please?
Best

**Comment by hassandraga** [comment]
You can now test the [C examples](https://github.com/alifcommunity/webui/tree/main/examples/C/call_c_from_js/macOS/Clang) in macOS.

```
cd examples/C/call_c_from_js/macOS/Clang
make
```

**Comment by MartyLake** [comment]
```
git pull
cd examples/C/call_c_from_js/macOS/Clang
make
./main #this works! so cool!
make debug
./main #this spawns a chrome window
```
is this expected ?

**Comment by AlbertShown** [comment]
Thank you for testing and reporting this. Yes, it's a minor issue described in the [PR](https://github.com/alifcommunity/webui/commit/c89d92fc80b47ab2056598d9cee1f7fffd214355).

> * [Issue] We need to close Chrome to run the program again. We need to find the perfect command to run Chrome to fix this

**What happens?**
When you run the program the first time, it will work, and the second run will show the home page.

**Workaround**
It will fix if you quit Chrome using the top left menu.

**Problem**
WebUI runs your browser like this: `open -W "/Applications/Google Chrome.app" --args --user-data-dir="/Users/mtt/.WebUI/WebUIChromeProfile" --no-first-run --disable-gpu --disable-software-rasterizer --no-proxy-server --safe-mode --disable-extensions --disable-background-mode --disable-plugins --disable-plugins-discovery --disable-translate --bwsi --disable-sync --incognito --app=https://www.wikipedia.org/ >>/dev/null 2>>/dev/null`.

Just copy and paste this command into your terminal, run (_You will see Wikipedia_), close the window [X] (_normal close_), then run the command again. You will probably see the home page instead of Wikipedia.

**Solution**
We need to tweak the command arguments until we solve the issue. But we prefer to keep `--incognito` as possible.

If you find the best command arguments, please share them with us here. Here is a [list of Chromium commands](https://peter.sh/experiments/chromium-command-line-switches/).

**Comment by hassandraga** [comment]
Same bug as https://github.com/alifcommunity/webui/issues/69.
